### ISSUE TITLE
Where are the files

### ISSUE THREAD

**Issue by uberflyx** [nerdyscout/KiCAD-CICD-Template#3]
Hi - thanks for this excellent template! I've set it up and been fiddling around to see how it works but not much luck. The actions all run with no errors, however, I can't find the generated files,,, I'm probably being silly about something that undocumented? Thanks

**Comment by nerdyscout** [comment]
hi @uberflyx 
please take a look here https://github.com/nerdyscout/KiCAD-CICD-Template_test/actions/runs/2314833017
on the very bottom the generated artifacts can be downloaded.
Please be aware github artifacts do have a lifetime and will be deleted after 90 days. so you might want to upload them somewhere else, build releases, commit them into the repository (dont do it, bad idea!), ...

if you still can not find the files please share your repository.
