### ISSUE TITLE
DCR and ERC fail with hierarchical sheets

### ISSUE THREAD

**Issue by Informaticore** [nerdyscout/KiCAD-CICD-Template#4]
I am using hierarchical sheets in my project but the DRC and ERC is failing with
`ERROR:Unknown output`

The hierarchical sheets are not called like the repository, of course they have there own name for each sheet. 
Am I missing configuration or is there a fix for that somehow?

**Comment by nerdyscout** [comment]
I guess you where able to figure out a solution by yourself according the [kibot issue](https://github.com/INTI-CMNB/KiBot/issues/321) ?

**Comment by dzid26** [comment]
I have hierarchical sheet too with multiple eschemas. 

I was getting the following error:
`ERROR:Unknown output/group`

I fixed it by pointing to actually file name env:
```
Env:
  schema: "PCB/board.kicad_sch"
  board: "PCB/board.kicad_pcb"
```

Per https://github.com/INTI-CMNB/KiBot/issues/321#issuecomment-1288907039
